[SCL-58] Auth0 Auth Backend
SpeciesConservationLandscapes/scl-api pull request #2
Opened 2019-12-03 17:02 UTC by gridcell

Trello Card: https://trello.com/c/tCyNPGwD/58-top-authentication-system

2019-12-03 17:03 UTC, gridcell commented
![](https://github.trello.services/images/mini-trello-icon.png) [TOP authentication system](https://trello.com/c/tCyNPGwD/58-top-authentication-system)

2019-12-04 00:11 UTC, saanobhaai requested changes
Just a couple of little things... and, might be worth checking that the auth0 stuff reflects latest templates/recipes, and not just copied from mermaid (I'm thinking of the recent Collect-side syncing you did)?

2019-12-04 00:11 UTC, saanobhaai commented on src/api/models/base.py
> +        db_table = "applications"
I've been deliberately letting django manage everything -- haven't even looked at pgadmin yet. I'd remove this.

2019-12-04 00:11 UTC, saanobhaai commented on .circleci/config.yml
> +      sudo pip install awscli==1.16.96 boto3==1.9.86 awsebcli==3.14.10 fabric==2.5.0
Still a bunch of aws-specific stuff in here...

2019-12-04 00:11 UTC, saanobhaai commented on .circleci/config.yml
> +          command: env > .env && fab buildnocache && fab up  && docker cp ./src/. api_service:/var/projects/webapp && sleep 10 && fab createdatabase && fab migrate
glad this worked

2019-12-04 20:12 UTC, merged